// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/device/ports.go
//
// Generated by this command:
//
//	mockgen -source=./src/device/ports.go -destination=./src/device/infrastructure/mocks/device_read_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	device "interFleet/src/device"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDeviceReadRepository is a mock of IDeviceReadRepository interface.
type MockIDeviceReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDeviceReadRepositoryMockRecorder
	isgomock struct{}
}

// MockIDeviceReadRepositoryMockRecorder is the mock recorder for MockIDeviceReadRepository.
type MockIDeviceReadRepositoryMockRecorder struct {
	mock *MockIDeviceReadRepository
}

// NewMockIDeviceReadRepository creates a new mock instance.
func NewMockIDeviceReadRepository(ctrl *gomock.Controller) *MockIDeviceReadRepository {
	mock := &MockIDeviceReadRepository{ctrl: ctrl}
	mock.recorder = &MockIDeviceReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeviceReadRepository) EXPECT() *MockIDeviceReadRepositoryMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockIDeviceReadRepository) GetById(id string) (*device.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*device.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIDeviceReadRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIDeviceReadRepository)(nil).GetById), id)
}
